const RAW='https://raw.githubusercontent.com/jandromani/InframundoShow/master/data/live.json';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number(v)||0));const deep=x=>JSON.parse(JSON.stringify(x));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const ALIASES={Spain:'ESP',Morocco:'MAR',Algeria:'DZA','United States of America':'USA','United States':'USA',Iran:'IRN',Israel:'ISR',China:'CHN',Taiwan:'TWN',Russia:'RUS',Ukraine:'UKR','North Korea':'PRK','Dem. Rep. Korea':'PRK','South Korea':'KOR','Republic of Korea':'KOR',Philippines:'PHL',India:'IND',Pakistan:'PAK',Serbia:'SRB','Bosnia and Herz.':'BIH','Bosnia and Herzegovina':'BIH','Dem. Rep. Congo':'COD','Democratic Republic of the Congo':'COD',Rwanda:'RWA',Venezuela:'VEN',Guyana:'GUY',Greece:'GRC',Turkey:'TUR','Türkiye':'TUR',Armenia:'ARM',Azerbaijan:'AZE',Ethiopia:'ETH',Eritrea:'ERI',Japan:'JPN','Saudi Arabia':'SAU',Egypt:'EGY',Germany:'DEU',France:'FRA',Italy:'ITA',Portugal:'PRT',Brazil:'BRA'};
const DIM_LABELS={score:'overall',diplomatic:'diplomatic',military:'military',territorial:'territorial',trade:'trade',energy:'energy',domestic:'domestic',information:'information'};
const DIM_LABELS_VECTOR={diplomatic:'diplomatic',military:'military',territorial:'territorial',trade:'trade',energy:'energy',domestic:'domestic',information:'information'};
const REST_LABELS={economic_interdependence:'economic dependence',alliance_mediation:'alliance / mediation',security_cooperation:'security cooperation',deterrence:'deterrence'};
const COLORS={score:'#ff5265',diplomatic:'#be7cff',military:'#ff5265',territorial:'#ff9c43',trade:'#2fe6a3',energy:'#ffd35d',domestic:'#3e9cff',information:'#39d7ff'};
const ROUTES=[
 {id:'atlantic-lng',name:'Atlantic LNG → Iberia',kind:'energy',subtype:'LNG shipping',points:[[-76,36],[-55,38],[-35,40],[-12,43],[-3.8,43.4]],countries:['USA','ESP'],gates:[],base:'open'},
 {id:'gulf-europe',name:'Gulf → Europe energy corridor',kind:'energy',subtype:'Oil / LNG shipping',points:[[52,26],[56.3,26.6],[61,20],[52,13],[43.4,12.6],[37,18],[33,29],[32.3,30.4],[23,34],[8,37],[-5.6,35.9],[-3.5,40]],countries:['IRN','ESP'],gates:['HORMUZ','BAB','SUEZ','GIBRALTAR'],base:'contested'},
 {id:'east-asia-europe',name:'East Asia → Europe maritime corridor',kind:'maritime',subtype:'Container / manufactured goods',points:[[121,31],[112,20],[104,3],[99,4],[83,8],[65,12],[43.4,12.6],[32.3,30.4],[12,37],[-5.6,35.9],[-8,43]],countries:['CHN','ESP','TUR'],gates:['MALACCA','BAB','SUEZ','GIBRALTAR'],base:'open'},
 {id:'west-africa-eu',name:'West Africa → Iberia LNG',kind:'energy',subtype:'LNG shipping',points:[[3,6],[-5,12],[-14,20],[-12,30],[-9,36],[-5.6,35.9],[-3.6,40]],countries:['ESP','MAR'],gates:['GIBRALTAR'],base:'open'},
 {id:'medgaz',name:'Medgaz',kind:'pipeline',subtype:'Gas pipeline',points:[[3.1,36.7],[1,36.2],[-2.5,36.8]],countries:['DZA','ESP'],gates:[],base:'open'},
 {id:'maghreb-europe',name:'Maghreb–Europe Gas Pipeline',kind:'pipeline',subtype:'Gas pipeline',points:[[2.5,33],[-1,34],[-5,34.5],[-5.6,35.9],[-4.5,37.3]],countries:['DZA','MAR','ESP'],gates:['GIBRALTAR'],base:'contested'},
 {id:'turkstream',name:'TurkStream',kind:'pipeline',subtype:'Gas pipeline',points:[[37,44],[31,42],[29,41],[26,42]],countries:['RUS','TUR'],gates:[],base:'open'},
 {id:'btc',name:'Baku–Tbilisi–Ceyhan',kind:'pipeline',subtype:'Oil pipeline',points:[[50,40.4],[45,41.7],[40,40],[35.9,36.8]],countries:['AZE','TUR'],gates:[],base:'open'},
 {id:'marea',name:'MAREA cable',kind:'cable',subtype:'Submarine data cable',points:[[-75.9,36.9],[-50,38],[-30,40],[-12,43],[-3.0,43.35]],countries:['USA','ESP'],gates:[],base:'open'},
 {id:'ellalink',name:'EllaLink',kind:'cable',subtype:'Submarine data cable',points:[[-9.1,38.7],[-18,28],[-25,12],[-31,-2],[-38.5,-3.7]],countries:['PRT','BRA','ESP'],gates:[],base:'open'},
 {id:'europe-asia-cable',name:'Europe–Asia data corridor',kind:'cable',subtype:'Submarine data cable',points:[[-3,43],[10,38],[25,34],[32.3,30.4],[43.4,12.6],[75,8],[101,3],[121,22]],countries:['ESP','CHN'],gates:['SUEZ','BAB','MALACCA'],base:'contested'},
 {id:'cape-reroute',name:'Cape of Good Hope reroute',kind:'maritime',subtype:'Strategic bypass',points:[[55,24],[65,10],[55,-10],[35,-35],[15,-35],[-5,-20],[-15,5],[-12,25],[-5.6,35.9]],countries:['ESP','USA','CHN'],gates:['GIBRALTAR'],base:'open'}
];
const NODES=[
 {id:'algeciras',name:'Port of Algeciras',type:'port',coord:[-5.44,36.13],country:'ESP'},{id:'tangermed',name:'Tanger Med',type:'port',coord:[-5.5,35.89],country:'MAR'},{id:'bilbao',name:'Bilbao / cable landing',type:'cable',coord:[-3.0,43.35],country:'ESP'},{id:'cartagena',name:'Cartagena LNG',type:'energy',coord:[-0.98,37.6],country:'ESP'},{id:'hassi',name:"Hassi R'Mel gas hub",type:'energy',coord:[3.27,32.94],country:'DZA'},{id:'fujairah',name:'Fujairah energy hub',type:'energy',coord:[56.33,25.13],country:'ARE'},{id:'suez-port',name:'Suez',type:'port',coord:[32.55,29.97],country:'EGY'},{id:'singapore',name:'Singapore',type:'port',coord:[103.8,1.25],country:'SGP'},{id:'shanghai',name:'Shanghai',type:'port',coord:[121.5,31.2],country:'CHN'},{id:'rotterdam',name:'Rotterdam',type:'port',coord:[4.48,51.92],country:'NLD'},{id:'virginia',name:'Virginia Beach cable landing',type:'cable',coord:[-75.98,36.85],country:'USA'}
];
const GATE_LABELS={HORMUZ:'Strait of Hormuz',SUEZ:'Suez Canal',BAB:'Bab el-Mandeb',MALACCA:'Strait of Malacca',GIBRALTAR:'Strait of Gibraltar',BOSPORUS:'Bosporus',TAIWAN:'Taiwan Strait',BLACKSEA:'Black Sea'};
ROUTES.push(
 {id:'transatlantic-container',name:'North Atlantic container corridor',kind:'trade',subtype:'Container shipping',points:[[-74,40],[-50,45],[-25,48],[-6,50],[4.4,52]],countries:['USA','GBR','FRA','DEU','NLD','ESP'],gates:[],base:'open'},
 {id:'pacific-us-china',name:'China ↔ U.S. Pacific corridor',kind:'trade',subtype:'Container / electronics',points:[[121,31],[145,32],[170,36],[-165,38],[-140,35],[-118,34]],countries:['CHN','USA','JPN'],gates:['TAIWAN'],base:'contested'},
 {id:'india-europe',name:'India → Europe maritime corridor',kind:'trade',subtype:'Manufactured goods / energy',points:[[72.8,19],[64,15],[55,13],[43.4,12.6],[32.3,30.4],[18,36],[-5.6,35.9]],countries:['IND','ESP','ITA','FRA','DEU'],gates:['BAB','SUEZ','GIBRALTAR'],base:'open'},
 {id:'blacksea-med',name:'Black Sea → Mediterranean corridor',kind:'maritime',subtype:'Grain / energy shipping',points:[[30.7,46.5],[29,43],[28.9,41],[26,39],[24,37],[19,36]],countries:['UKR','RUS','TUR','ROU','BGR'],gates:['BOSPORUS','BLACKSEA'],base:'contested'},
 {id:'northsea-med',name:'North Sea → Western Mediterranean',kind:'trade',subtype:'European maritime trade',points:[[4.4,52],[1,50],[-5,46],[-9,43],[-9,38],[-5.6,35.9],[2,39]],countries:['NLD','GBR','FRA','ESP','MAR'],gates:['GIBRALTAR'],base:'open'},
 {id:'transmed',name:'TransMed gas pipeline',kind:'pipeline',subtype:'Gas pipeline',points:[[3,33],[8,34],[10,37],[12,39],[13,42]],countries:['DZA','TUN','ITA'],gates:[],base:'open'},{id:'tap',name:'Trans Adriatic Pipeline',kind:'pipeline',subtype:'Gas pipeline',points:[[20,40.5],[18,40],[15.5,40],[12,41]],countries:['AZE','GRC','ALB','ITA'],gates:[],base:'open'},{id:'power-siberia',name:'Power of Siberia',kind:'pipeline',subtype:'Gas pipeline',points:[[129,62],[126,55],[123,49],[120,45],[117,43]],countries:['RUS','CHN'],gates:[],base:'open'},{id:'nordstream',name:'Nord Stream corridor',kind:'pipeline',subtype:'Gas pipeline · inactive model',points:[[28,60],[23,58],[18,56],[13,54]],countries:['RUS','DEU'],gates:[],base:'blocked'},
 {id:'seamewe5',name:'SEA-ME-WE 5 cable',kind:'cable',subtype:'Submarine data cable',points:[[103.8,1.2],[80,7],[57,12],[43.4,12.6],[32.3,30.4],[20,36],[5,40],[-5,43]],countries:['SGP','IND','EGY','ITA','FRA','ESP'],gates:['MALACCA','BAB','SUEZ'],base:'open'},{id:'africa-cable',name:'2Africa / Atlantic cable ring',kind:'cable',subtype:'Submarine data cable',points:[[-9,38],[-17,28],[-17,10],[-9,-10],[18,-34],[34,-25],[40,-10],[43,8],[43.4,12.6],[32.3,30.4],[8,38]],countries:['ESP','PRT','MAR','ZAF','EGY','ITA'],gates:['BAB','SUEZ','GIBRALTAR'],base:'open'}
);
NODES.push({id:'valencia',name:'Port of Valencia',type:'port',coord:[-0.32,39.44],country:'ESP'},{id:'barcelona-port',name:'Port of Barcelona',type:'port',coord:[2.17,41.35],country:'ESP'},{id:'port-said',name:'Port Said',type:'port',coord:[32.3,31.25],country:'EGY'},{id:'jebel-ali',name:'Jebel Ali',type:'port',coord:[55.03,25.0],country:'ARE'},{id:'ras-tanura',name:'Ras Tanura oil terminal',type:'energy',coord:[50.17,26.64],country:'SAU'},{id:'mumbai',name:'Mumbai / Nhava Sheva',type:'port',coord:[72.9,18.95],country:'IND'},{id:'busan',name:'Busan',type:'port',coord:[129.05,35.1],country:'KOR'},{id:'los-angeles',name:'Los Angeles / Long Beach',type:'port',coord:[-118.25,33.75],country:'USA'},{id:'cape-town',name:'Cape Town',type:'port',coord:[18.43,-33.92],country:'ZAF'},{id:'durban',name:'Durban',type:'port',coord:[31.03,-29.86],country:'ZAF'},{id:'lagos',name:'Lagos',type:'port',coord:[3.39,6.45],country:'NGA'},{id:'piraeus',name:'Piraeus',type:'port',coord:[23.63,37.94],country:'GRC'});
const STATIC_CHOKES=[{id:'HORMUZ',name:'Strait of Hormuz',coord:[56.25,26.56],domains:['energy','trade'],score:88},{id:'SUEZ',name:'Suez Canal',coord:[32.35,30.4],domains:['trade','energy'],score:72},{id:'BAB',name:'Bab el-Mandeb',coord:[43.35,12.6],domains:['trade','energy'],score:76},{id:'MALACCA',name:'Strait of Malacca',coord:[101.1,2.8],domains:['trade','energy'],score:62},{id:'GIBRALTAR',name:'Strait of Gibraltar',coord:[-5.6,35.95],domains:['trade','energy'],score:48},{id:'BOSPORUS',name:'Bosporus',coord:[29.05,41.1],domains:['trade','energy'],score:55},{id:'TAIWAN',name:'Taiwan Strait',coord:[119.8,24.0],domains:['trade','military'],score:79}];
let live=null,world=null,mode='live',selectedId=null,player='ESP',focusCountry='ESP',layer='score',sim=null,highlightPairs=[],selectedRoute=null;
let mapLayers={tensions:true,tradeRoutes:true,energyRoutes:true,maritime:true,pipelines:true,cables:true,elections:true,dependencies:true};
let svg=null,mapStage=null,landG=null,depG=null,routeG=null,edgeG=null,chokeG=null,infraG=null,electionG=null,shipG=null,labelG=null,countryPaths=[];
let mapTransform={x:0,y:0,scale:1},mapDrag=null,shipModels=[],shipRAF=0,autoplay=false,autoTimer=null,simSpeed=12000;
async function fetchState(){for(const url of ['./data/live.json?t='+Date.now(),RAW+'?t='+Date.now()]){try{const r=await fetch(url,{cache:'no-store'});if(r.ok)return await r.json()}catch{}}throw new Error('Unable to load world state')}
const C=code=>world?.countries?.[code]||live?.countries?.[code]||{name:code,flag:'',coord:[0,0],economy_live:50,stability_live:50};const pair=id=>(world?.pairs||[]).find(p=>p.id===id);const fronts=code=>(world?.pairs||[]).filter(p=>p.a===code||p.b===code).sort((a,b)=>b.score-a.score);const pairBetween=(a,b)=>(world?.pairs||[]).find(p=>(p.a===a&&p.b===b)||(p.a===b&&p.b===a));const val=p=>layer==='score'?p.score:(p.vector?.[layer]??p.score);const scoreColor=v=>v>=90?'#ff5265':v>=78?'#ff9c43':v>=65?'#ffd35d':v>=50?'#be7cff':'#173a48';const fmt=x=>{try{return new Intl.DateTimeFormat('es-ES',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x))}catch{return x||'—'}};const safeUrl=u=>{try{const x=new URL(u);return /^https?:$/.test(x.protocol)?x.href:'#'}catch{return '#'}};
function relationOverall(p){const w={diplomatic:.17,military:.23,territorial:.18,trade:.10,energy:.09,domestic:.11,information:.07};let raw=Object.entries(w).reduce((s,[k,x])=>s+clamp(p.vector?.[k])*x,0)+(Number(p.gearwatch_pressure)||0)*.16;const r=Object.values(p.restraints||{}).map(Number).filter(Number.isFinite);if(r.length)raw-=r.reduce((a,b)=>a+b,0)/r.length*.055;return Math.round(clamp(raw))}function ensureSelected(){if(!selectedId||!pair(selectedId))selectedId=(world?.pairs||[]).slice().sort((a,b)=>b.score-a.score)[0]?.id||null}function dominantDimension(p){return Object.entries(p?.vector||{}).sort((a,b)=>b[1]-a[1])[0]?.[0]||'diplomatic'}function findChoke(gate){return (world?.chokepoints||[]).find(c=>String(c.id||c.name).toUpperCase().includes(gate)||String(c.name).toUpperCase().includes(GATE_LABELS[gate]?.toUpperCase().replace('STRAIT OF ','')||gate))}
function routeGlobalStatus(route){let status=route.base||'open';const scores=(route.gates||[]).map(findChoke).filter(Boolean).map(x=>Number(x.score)||0),max=scores.length?Math.max(...scores):0;if(max>=94)status='blocked';else if(max>=70&&status!=='blocked')status='contested';if(route.id==='maghreb-europe'&&(pairBetween('MAR','DZA')?.score||0)>=65)status='contested';return status}
function routeAccess(route,code=focusCountry){let status=routeGlobalStatus(route),reason=status==='open'?'Strategic corridor operating normally in the model.':status==='contested'?'Route faces elevated geopolitical or chokepoint pressure.':'Route is severely constrained by current modeled pressure.';const override=mode==='sim'&&sim?.route_overrides?.[route.id]?.[code];if((route.gates||[]).includes('HORMUZ')){const usIran=pairBetween('USA','IRN')?.score||0;if(code==='USA'&&usIran>=72){status='blocked';reason='Country-specific access: U.S.–Iran confrontation closes this modeled Hormuz corridor to U.S.-linked traffic.'}else if(code==='ESP'){status=status==='blocked'?'contested':'open';reason='Country-specific access: Spain retains modeled passage while U.S.-linked traffic faces greater restriction.'}else if(code==='IRN'){status='open';reason='Iran retains domestic access to the Gulf corridor in this model.'}}if((route.gates||[]).includes('TAIWAN')){const ct=pairBetween('CHN','TWN')?.score||0;if(code==='TWN'&&ct>=84){status='contested';reason='Taiwan Strait military pressure raises insurance and routing friction.'}if(code==='CHN'&&ct>=92){status='contested';reason='High cross-strait pressure constrains commercial routing despite domestic access.'}}if((route.gates||[]).includes('GIBRALTAR')&&(code==='ESP'||code==='MAR')){const em=pairBetween('ESP','MAR')?.score||0;if(em>=85){status=status==='blocked'?'blocked':'contested';reason='Spain–Morocco pressure raises local routing and insurance friction around Gibraltar.'}}if(route.id==='maghreb-europe'&&(code==='MAR'||code==='DZA'||code==='ESP')){const md=pairBetween('MAR','DZA')?.score||0;if(md>=65){status='contested';reason='Maghreb rivalry materially constrains this modeled pipeline corridor.'}}if(route.id==='blacksea-med'){const ru=pairBetween('RUS','UKR')?.score||0;if(ru>=80){status='contested';reason='Russia–Ukraine conflict pressure constrains Black Sea commercial flows.'}}if(override){status=override.status||status;reason=override.reason||reason}return{status,reason,via:override?.via||null}}
function routeVisible(r){if(r.kind==='cable')return mapLayers.cables;if(r.kind==='pipeline')return mapLayers.pipelines;if(r.kind==='energy')return mapLayers.energyRoutes;if(r.kind==='maritime')return mapLayers.maritime||mapLayers.tradeRoutes;return true}
