const RAW='https://raw.githubusercontent.com/jandromani/InframundoShow/master/data/live.json';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number(v)||0));const deep=x=>JSON.parse(JSON.stringify(x));
const ALIASES={Spain:'ESP',Morocco:'MAR',Algeria:'DZA','United States of America':'USA','United States':'USA',Iran:'IRN',Israel:'ISR',China:'CHN',Taiwan:'TWN',Russia:'RUS',Ukraine:'UKR','North Korea':'PRK','Dem. Rep. Korea':'PRK','South Korea':'KOR','Republic of Korea':'KOR',Philippines:'PHL',India:'IND',Pakistan:'PAK',Serbia:'SRB','Bosnia and Herz.':'BIH','Bosnia and Herzegovina':'BIH','Dem. Rep. Congo':'COD','Democratic Republic of the Congo':'COD',Rwanda:'RWA',Venezuela:'VEN',Guyana:'GUY',Greece:'GRC',Turkey:'TUR','Türkiye':'TUR',Armenia:'ARM',Azerbaijan:'AZE',Ethiopia:'ETH',Eritrea:'ERI'};
const DIM_LABELS={score:'overall',diplomatic:'diplomatic',military:'military',territorial:'territorial',trade:'trade',energy:'energy',domestic:'domestic',information:'information'};
const REST_LABELS={economic_interdependence:'economic dependence',alliance_mediation:'alliance / mediation',security_cooperation:'security cooperation',deterrence:'deterrence'};
const COLORS={score:'#ff6f7d',diplomatic:'#b59cff',military:'#ff6f7d',territorial:'#ffad5a',trade:'#63e1a4',energy:'#ffd166',domestic:'#6da8ff',information:'#5bdcff'};
let live=null,world=null,mode='live',selectedId=null,player='ESP',layer='score',sim=null,highlightPairs=[];
let d3,topo,projection,path,svg,g,landG,edgeG,chokeG,labelG,countryPaths,zoom;

async function fetchState(){for(const url of [RAW+'?t='+Date.now(),'./data/live.json?t='+Date.now()]){try{const r=await fetch(url,{cache:'no-store'});if(r.ok)return await r.json()}catch{}}throw new Error('Unable to load world state')}
const C=code=>world?.countries?.[code]||live?.countries?.[code]||{name:code,flag:'',coord:[0,0]};
const pair=id=>(world?.pairs||[]).find(p=>p.id===id);const fronts=code=>(world?.pairs||[]).filter(p=>p.a===code||p.b===code).sort((a,b)=>b.score-a.score);
const val=p=>layer==='score'?p.score:(p.vector?.[layer]??p.score);const scoreColor=v=>v>=90?'#ff6f7d':v>=78?'#ffad5a':v>=65?'#ffd166':v>=50?'#b59cff':'#365361';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function safeUrl(u){try{const x=new URL(u);return /^https?:$/.test(x.protocol)?x.href:'#'}catch{return '#'}}
function fmt(x){try{return new Intl.DateTimeFormat('es-ES',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x))}catch{return x||'—'}}
function relationOverall(p){const w={diplomatic:.17,military:.23,territorial:.18,trade:.10,energy:.09,domestic:.11,information:.07};let raw=Object.entries(w).reduce((s,[k,x])=>s+clamp(p.vector?.[k])*x,0)+(Number(p.gearwatch_pressure)||0)*.16;const r=Object.values(p.restraints||{}).map(Number).filter(Number.isFinite);if(r.length)raw-=r.reduce((a,b)=>a+b,0)/r.length*.055;return Math.round(clamp(raw))}
function ensureSelected(){if(!selectedId||!pair(selectedId))selectedId=(world?.pairs||[]).slice().sort((a,b)=>b.score-a.score)[0]?.id||null}

function renderKpis(){const x=world?.global||{};$('#riskKpi').textContent=Math.round(x.risk||0);$('#shipKpi').textContent=Math.round(x.shipping_stress||0);$('#energyKpi').textContent=Math.round(x.energy_stress||0);$('#tradeKpi').textContent=Math.round(x.trade_stress||0);$('#politicalKpi').textContent=Math.round(x.political_stress||0);$('#memoryKpi').textContent=(world?.history||[]).length;$('#updatedChip').textContent=(mode==='live'?'LIVE ':'FORK ')+fmt(world?.updated_at||sim?.sim_date);$('#modeText').textContent=mode==='live'?'LIVE WORLD':`SIM · ${C(player).flag} ${C(player).name}`}
function bars(obj,labels,kind='vectors'){return Object.entries(labels).map(([k,label])=>{const v=Math.round(obj?.[k]||0);return`<div class="vector"><div class="vectorhead"><span>${esc(label)}</span><b>${v}</b></div><div class="track"><div class="fill" style="width:${clamp(v)}%"></div></div></div>`}).join('')}
function renderFront(){ensureSelected();const p=pair(selectedId);if(!p)return;const a=C(p.a),b=C(p.b);$('#frontTitle').textContent=`${a.flag} ${a.name} ↔ ${b.flag} ${b.name}`;$('#frontScore').textContent=Math.round(p.score);$('#frontScore').style.color=scoreColor(p.score);const tr=Number(p.trend||0);$('#frontTrend').className='small trend '+(tr>0?'up':tr<0?'down':'');$('#frontTrend').textContent=`${tr>0?'▲ +':tr<0?'▼ ':'→ '}${tr} · ${p.scan_articles||0} fresh signals · GW ${Math.round(p.gearwatch_pressure||0)}`;$('#frontSummary').textContent=p.summary||'No summary.';$('#frontDomains').innerHTML=(p.domains||p.domain||[]).map(x=>`<span>${esc(x)}</span>`).join('');$('#vectors').innerHTML=bars(p.vector,DIM_LABELS_VECTOR);$('#restraints').innerHTML=bars(p.restraints,REST_LABELS,'restraints');$('#drivers').innerHTML=(p.drivers||[]).map(x=>`<div class="driver">${esc(x)}</div>`).join('');$('#botMoves').innerHTML=(p.bot_moves||[]).map(x=>`<div>⚙ ${esc(x)}</div>`).join('')||'<div>No strategic move stored.</div>';$('#news').innerHTML=(p.news||[]).slice(0,7).map(n=>`<a href="${safeUrl(n.url)}" target="_blank" rel="noopener"><b>${esc(n.title)}</b><br><span>${esc(n.source||'')} · ${esc(String(n.seen||'').slice(0,10))}</span></a>`).join('')||'<div>No fresh article attached.</div>';$('#pairGear').innerHTML=(p.gearwatch_impacts||[]).map(x=>`<span class="pill">⚙ ${esc(x.label)} ${Math.round(x.score)}</span>`).join('')||'<span class="small muted">No direct GearWatch mechanism mapped.</span>';renderActions(p)}
const DIM_LABELS_VECTOR={diplomatic:'diplomatic',military:'military',territorial:'territorial',trade:'trade',energy:'energy',domestic:'domestic',information:'information'};
function renderRanking(){const rows=(world?.pairs||[]).slice().sort((a,b)=>val(b)-val(a));$('#ranking').innerHTML=rows.map((p,i)=>`<div class="rankrow" data-id="${p.id}"><b>#${i+1}</b><div><div>${C(p.a).flag} ${C(p.a).name} ↔ ${C(p.b).flag} ${C(p.b).name}</div><div class="rankbar"><i style="width:${clamp(val(p))}%"></i></div></div><b style="color:${scoreColor(val(p))}">${Math.round(val(p))}</b></div>`).join('');$$('.rankrow').forEach(el=>el.onclick=()=>{selectedId=el.dataset.id;highlightPairs=[];renderFront();renderMap()})}
function renderGear(){const gw=world?.gearwatch||{};$('#gearHeadline').textContent=gw.headline||'GearWatch causal radar';$('#gearBrief').textContent=gw.briefing||'';const arr=(gw.mechanisms||[]).filter(m=>m.impact_map).slice(0,12);$('#gearBoard').innerHTML=arr.map(m=>{const ids=m.impact_map?.pairs||[];const dims=Object.keys(m.impact_map?.domains||{}).join(' · ');return`<div class="gearitem" data-gw="${m.id}"><div class="row" style="justify-content:space-between"><b>${esc(m.label||m.id)}</b><span class="gscore">${Math.round(m.score||0)}</span></div><div class="small muted">${esc(m.state||'')} ${Number(m.delta)>0?'· ▲ '+m.delta:''}</div><div class="small">${esc(dims)}</div><div class="impactlist">${ids.slice(0,5).map(id=>`<span>${esc(id)}</span>`).join('')}</div></div>`}).join('')||'<div class="muted">No mapped causal mechanisms.</div>';$$('.gearitem').forEach(el=>el.onclick=()=>{const m=(gw.mechanisms||[]).find(x=>x.id===el.dataset.gw);if(!m)return;highlightPairs=m.impact_map?.pairs||[];const dims=Object.entries(m.impact_map?.domains||{}).sort((a,b)=>b[1]-a[1]);if(dims[0])setLayer(dims[0][0]);const hot=highlightPairs.map(id=>pair(id)).filter(Boolean).sort((a,b)=>b.score-a.score)[0];if(hot)selectedId=hot.id;$('#causalPulse').innerHTML=`<b>${esc(m.label)}</b> · causal ${Math.round(m.score||0)}/100 · ${esc(m.state||'')}<br><span class="muted">Pressure mapped to ${(m.impact_map?.pairs||[]).join(', ')||'no bilateral fronts'}${(m.impact_map?.chokes||[]).length?' · chokepoints '+m.impact_map.chokes.join(', '):''}</span>`;render()})}
function renderChokes(){const arr=(world?.chokepoints||[]).slice().sort((a,b)=>b.score-a.score);$('#chokes').innerHTML=arr.map(c=>`<div class="choke"><div class="row" style="justify-content:space-between"><b>${esc(c.name)}</b><strong style="color:${scoreColor(c.score)}">${Math.round(c.score)}</strong></div><div class="small muted">GW pressure ${Math.round((c.gearwatch_pressure||0)*10)/10}</div></div>`).join('')}
function renderCountries(){const arr=Object.entries(world?.countries||{}).sort((a,b)=>b[1].max_front-a[1].max_front).slice(0,12);$('#countries').innerHTML=arr.map(([code,c])=>`<div class="countrycard" data-code="${code}"><b>${c.flag} ${esc(c.name)}</b><div class="small muted">max front ${c.max_front} · avg ${c.pressure}</div><div class="small">stability ${c.stability_live} · economy ${c.economy_live}</div></div>`).join('');$$('.countrycard').forEach(el=>el.onclick=()=>selectCountry(el.dataset.code))}
function selectCountry(code){const fs=fronts(code);if(fs[0])selectedId=fs[0].id;if(mode==='sim'){player=code;sim.sim_log.unshift(`You take control of ${C(code).name}.`)}render()}
function renderSpark(){const h=(world?.history||[]).slice(-72);const s=$('#spark');if(!h.length){s.innerHTML='';return}const w=600,hh=110;const vals=h.map(x=>Number(x.global_risk??0));const min=Math.min(...vals,0),max=Math.max(...vals,100);const pts=vals.map((v,i)=>[i/(Math.max(1,vals.length-1))*w,hh-((v-min)/(Math.max(1,max-min)))*(hh-12)-6]);const d=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+','+p[1].toFixed(1)).join(' ');s.innerHTML=`<line x1="0" y1="55" x2="600" y2="55"></line><path d="${d}"></path>`;$('#historyLabel').textContent=`${h.length} snapshots · risk ${vals[0]||'—'} → ${vals.at(-1)||'—'}`}
function renderSim(){if(mode!=='sim')return;$('#simDate').textContent=sim.sim_date;$('#simLog').innerHTML=(sim.sim_log||[]).slice(0,14).map(x=>`<div>${esc(x)}</div>`).join('')}
function renderActions(p){if(mode!=='sim')return;const involved=p.a===player||p.b===player;const other=p.a===player?p.b:p.a;const acts=involved?[['talks','Open de-escalation channel','↓ diplomatic, ↑ mediation'],['pressure','Economic pressure','↑ trade + diplomatic pressure'],['readiness','Military readiness','↑ military + deterrence'],['energy','Energy shield','↓ energy vulnerability']]:[['mediate','Offer mediation','↓ diplomatic; ↑ mediation restraint']];$('#actions').innerHTML=`<div class="small muted">Acting as ${C(player).flag} ${C(player).name}${involved?' vs '+C(other).name:' on a third-party front'}.</div>`+acts.map(a=>`<button class="action" data-act="${a[0]}"><b>${a[1]}</b><div class="small muted">${a[2]}</div></button>`).join('');$$('.action[data-act]').forEach(b=>b.onclick=()=>applyAction(p.id,b.dataset.act))}
function applyAction(id,act){const p=pair(id);if(!p||mode!=='sim')return;let txt='';if(act==='talks'){p.vector.diplomatic=clamp(p.vector.diplomatic-12);p.vector.domestic=clamp(p.vector.domestic-2);p.restraints.alliance_mediation=clamp(p.restraints.alliance_mediation+6);txt=`${C(player).name} opens a de-escalation channel on ${id}.`}if(act==='pressure'){p.vector.trade=clamp(p.vector.trade+11);p.vector.diplomatic=clamp(p.vector.diplomatic+5);p.restraints.economic_interdependence=clamp(p.restraints.economic_interdependence-4);txt=`${C(player).name} applies economic pressure on ${id}.`}if(act==='readiness'){p.vector.military=clamp(p.vector.military+12);p.restraints.deterrence=clamp(p.restraints.deterrence+7);txt=`${C(player).name} raises military readiness on ${id}.`}if(act==='energy'){p.vector.energy=clamp(p.vector.energy-9);const c=world.countries[player];if(c)c.energy_security=clamp(c.energy_security+4);txt=`${C(player).name} launches an energy resilience package.`}if(act==='mediate'){p.vector.diplomatic=clamp(p.vector.diplomatic-6);p.restraints.alliance_mediation=clamp(p.restraints.alliance_mediation+8);txt=`${C(player).name} offers mediation on ${id}.`}const old=p.score;p.score=relationOverall(p);p.trend=p.score-old;sim.sim_log.unshift(txt);recalcSimulation();render()}
function rnd(seed){let x=seed>>>0;return()=>{x=(x*1664525+1013904223)>>>0;return x/4294967296}}
function resolveWeek(){if(mode!=='sim')return;const d=new Date(sim.sim_date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+7);sim.sim_date=d.toISOString().slice(0,10);const r=rnd(Number(sim.sim_date.replaceAll('-','')));for(const p of sim.pairs){const old=p.score;const top=Object.entries(p.vector||{}).sort((a,b)=>b[1]-a[1])[0]?.[0]||'diplomatic';const restraint=Object.values(p.restraints||{}).reduce((a,b)=>a+Number(b||0),0)/4;const drift=(r()-.48)*7-(restraint-55)*.018;const gear=(p.gearwatch_impacts||[]).reduce((s,x)=>s+(x.state==='ACTIVE'||x.state==='ARMING'?Number(x.pressure||0):0),0)*.035;p.vector[top]=clamp(p.vector[top]+drift+gear);p.score=relationOverall(p);p.trend=p.score-old}recalcSimulation();const hot=sim.pairs.slice().sort((a,b)=>b.score-a.score)[0];sim.sim_log.unshift(`Bots resolve week ending ${sim.sim_date}. Highest front: ${hot.id} ${hot.score}/100.`);selectedId=pair(selectedId)?.id||hot.id;render()}
function recalcSimulation(){const ps=world.pairs,scores=ps.map(p=>p.score),avg=scores.reduce((a,b)=>a+b,0)/scores.length,hot=Math.max(...scores);world.global.risk=Math.round(clamp(avg*.58+hot*.42));const ch=world.chokepoints||[];world.global.shipping_stress=Math.round(ch.reduce((s,c)=>s+c.score,0)/Math.max(1,ch.length));const e=ch.filter(c=>c.domains?.includes('energy'));world.global.energy_stress=Math.round(e.reduce((s,c)=>s+c.score,0)/Math.max(1,e.length));const t=ch.filter(c=>c.domains?.includes('trade'));world.global.trade_stress=Math.round(t.reduce((s,c)=>s+c.score,0)/Math.max(1,t.length))}
function setMode(next){mode=next;document.body.classList.toggle('sim',next==='sim');$('#liveBtn').classList.toggle('active',next==='live');$('#simBtn').classList.toggle('active',next==='sim');if(next==='sim'){sim=deep(live);world=sim;player='ESP';sim.sim_date=(live.updated_at||new Date().toISOString()).slice(0,10);sim.sim_log=[`Fork created from LIVE snapshot. You control ${C(player).name}.`]}else{world=live;sim=null}ensureSelected();render()}
function setLayer(next){layer=next;$$('.layer').forEach(b=>b.classList.toggle('active',b.dataset.layer===layer));$('#layerName').textContent=DIM_LABELS[layer]||layer;renderRanking();renderMap()}
function render(){renderKpis();renderFront();renderRanking();renderGear();renderChokes();renderCountries();renderSpark();renderSim();renderMap()}

async function initMap(){try{[d3,topo,{default:atlas}]=await Promise.all([import('https://cdn.jsdelivr.net/npm/d3@7.9.0/+esm'),import('https://cdn.jsdelivr.net/npm/topojson-client@3.1.0/+esm'),import('https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-50m.json/+esm')]);const features=topo.feature(atlas,atlas.objects.countries).features;projection=d3.geoNaturalEarth1().fitExtent([[12,12],[1188,668]],{type:'Sphere'});path=d3.geoPath(projection);svg=d3.select('#worldMap');svg.selectAll('*').remove();svg.append('path').datum({type:'Sphere'}).attr('d',path).attr('fill','#03090d').attr('stroke','#18303d');g=svg.append('g');landG=g.append('g');edgeG=g.append('g');chokeG=g.append('g');labelG=g.append('g');countryPaths=landG.selectAll('path').data(features).join('path').attr('d',path).attr('class','country').on('click',(ev,d)=>{const code=ALIASES[d.properties?.name];if(code&&world?.countries?.[code])selectCountry(code)});zoom=d3.zoom().scaleExtent([1,9]).on('zoom',ev=>g.attr('transform',ev.transform));svg.call(zoom);$('#zoomIn').onclick=()=>svg.transition().duration(150).call(zoom.scaleBy,1.45);$('#zoomOut').onclick=()=>svg.transition().duration(150).call(zoom.scaleBy,.69);$('#zoomReset').onclick=()=>svg.transition().duration(150).call(zoom.transform,d3.zoomIdentity);renderMap()}catch(err){console.error(err);$('#worldMap').replaceWith(Object.assign(document.createElement('div'),{className:'muted',textContent:'Map engine failed; ranking and simulation still work.'}))}}
function mapCountryValue(code){const fs=fronts(code);return fs.length?Math.max(...fs.map(p=>val(p))):0}
function renderMap(){if(!countryPaths||!world)return;countryPaths.attr('fill',d=>{const code=ALIASES[d.properties?.name];if(!code||!world.countries?.[code])return '#08131a';return scoreColor(mapCountryValue(code))}).attr('opacity',d=>ALIASES[d.properties?.name]&&world.countries?.[ALIASES[d.properties.name]]?.pressure?1:.62).attr('class',d=>{const code=ALIASES[d.properties?.name];return'country'+(mode==='sim'&&code===player?' player':'')});const data=world.pairs||[];edgeG.selectAll('path').data(data,d=>d.id).join(enter=>enter.append('path').attr('class','edge').on('click',(ev,d)=>{ev.stopPropagation();selectedId=d.id;highlightPairs=[];render()}),update=>update,exit=>exit.remove()).attr('class',d=>'edge'+(d.id===selectedId?' selected':'')).attr('d',d=>{const a=C(d.a).coord,b=C(d.b).coord;return path({type:'LineString',coordinates:[a,b]})}).attr('stroke',d=>highlightPairs.includes(d.id)?'#ffffff':COLORS[layer]||scoreColor(val(d))).attr('stroke-width',d=>1+val(d)/27+(highlightPairs.includes(d.id)?2:0)).attr('stroke-dasharray',d=>val(d)<55?'5 4':null);const cg=chokeG.selectAll('g.chokepoint').data(world.chokepoints||[],d=>d.id).join(enter=>{const q=enter.append('g').attr('class','chokepoint');q.append('rect').attr('x',-4).attr('y',-4).attr('width',8).attr('height',8).attr('transform','rotate(45)').attr('stroke','#02070a').attr('stroke-width',1.5);q.append('text').attr('class','chokelabel').attr('x',8).attr('y',3);return q},update=>update,exit=>exit.remove()).attr('transform',d=>{const p=projection(d.coord);return`translate(${p[0]},${p[1]})`});cg.select('rect').attr('fill',d=>scoreColor(d.score));cg.select('text').text(d=>`${d.name} ${Math.round(d.score)}`);const labs=Object.entries(world.countries||{}).filter(([code])=>mapCountryValue(code)>=65);labelG.selectAll('text.maplabel').data(labs,d=>d[0]).join('text').attr('class','maplabel').attr('text-anchor','middle').attr('x',d=>projection(d[1].coord)[0]).attr('y',d=>projection(d[1].coord)[1]-7).text(d=>d[1].flag)}

async function init(){live=await fetchState();world=live;ensureSelected();$('#liveBtn').onclick=()=>setMode('live');$('#simBtn').onclick=()=>setMode('sim');$('#refreshBtn').onclick=async()=>{live=await fetchState();if(mode==='live')world=live;render()};$('#nextTurn').onclick=resolveWeek;$$('.layer').forEach(b=>b.onclick=()=>setLayer(b.dataset.layer));render();await initMap()}
init().catch(err=>{console.error(err);document.body.innerHTML=`<div style="padding:30px;color:white;background:#04080c;font-family:system-ui"><h1>WORLD//STATE failed to initialise</h1><pre>${esc(err.message)}</pre></div>`});
